// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6eO2A7TwNN3oCJzjw0Wb75L9kJ0pDgp8',
    appId: '1:845351026928:web:9f97c16cd91b102ae30235',
    messagingSenderId: '845351026928',
    projectId: 'finner-9c385',
    authDomain: 'finner-9c385.firebaseapp.com',
    storageBucket: 'finner-9c385.appspot.com',
    measurementId: 'G-60QGRT7SYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg41aB70T_HRaWIglwzf1-MGOFpL0AHLk',
    appId: '1:845351026928:android:8006c4dbeb47db33e30235',
    messagingSenderId: '845351026928',
    projectId: 'finner-9c385',
    storageBucket: 'finner-9c385.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQAe9kSEcU7UTDXw85PM-_QV4jwDKPi9c',
    appId: '1:845351026928:ios:91246d52b69b332de30235',
    messagingSenderId: '845351026928',
    projectId: 'finner-9c385',
    storageBucket: 'finner-9c385.appspot.com',
    iosClientId: '845351026928-litipp3b2dtaiiajcevoptbiglusb54g.apps.googleusercontent.com',
    iosBundleId: 'com.mateuszficek.finner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQAe9kSEcU7UTDXw85PM-_QV4jwDKPi9c',
    appId: '1:845351026928:ios:91246d52b69b332de30235',
    messagingSenderId: '845351026928',
    projectId: 'finner-9c385',
    storageBucket: 'finner-9c385.appspot.com',
    iosClientId: '845351026928-litipp3b2dtaiiajcevoptbiglusb54g.apps.googleusercontent.com',
    iosBundleId: 'com.mateuszficek.finner',
  );
}
